version: '3'

networks:
  backend:

services:
  rabbit:
    image: rabbitmq:3.9.13-management
    container_name: rabbitmq
    profiles: ["main", "init"]
    networks:
      - backend

  db:
    build: ./services/postgres
    container_name: postgres
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.env

  admin:
    build: ./admin
    profiles: ["main", "init"]
    networks:
      - backend
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - db

  admin-migrate:
    build: ./admin
    profiles: ["init"]
    networks:
      - backend
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    entrypoint: ["./entrypoint.sh", "migrate"]
    depends_on:
      - db

  actions_api:
    build: ./actions_api
    profiles: ["main", "init"]
    networks:
      - backend
    volumes:
      - ./actions_api:/usr/src/actions_api/
    env_file:
      - ./actions_api/.env
    depends_on:
      - db

  event_generator:
    build: ./event_generator
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./event_generator:/usr/src/event_generator/
    env_file:
      - ./event_generator/.env
    depends_on:
      - db

  publisher:
    build: ./publisher
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./publisher:/usr/src/publisher/
    env_file:
      - ./publisher/.env
    depends_on:
      - db
      - rabbit

  events_etl:
    build: ./events_etl
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./events_etl:/usr/src/events_etl/
    env_file:
      - ./events_etl/.env
    depends_on:
      - db
      - publisher

  consumer:
    build: ./consumer
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./consumer:/usr/src/consumer/
    env_file:
      - ./consumer/.env
    depends_on:
      - rabbit

  consumer2:
    build: ./consumer
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./consumer:/usr/src/consumer/
    environment:
      - RABBIT_USERNAME=rabbit
      - RABBIT_PASSWORD=rabbit
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_EXCHANGE=
      - RABBIT_ROUTING=other
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_USER=test@gmail.com
      - SMTP_PASSWORD=12345678
    depends_on:
      - rabbit

  nginx:
    build: ./services/nginx
    profiles: ["main", "init"]
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/admin/static
    depends_on:
      - admin
      - actions_api

volumes:
  postgres_volume:
  static_volume: