version: '3'

networks:
  backend:

services:
  db:
    build: ./services/postgres
    container_name: postgres
    profiles: ["main", "init"]
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.env

  admin:
    build: ./admin
    profiles: ["main", "init"]
    networks:
      - backend
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      - db

  admin-migrate:
    build: ./admin
    profiles: ["init"]
    networks:
      - backend
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    entrypoint: ["./entrypoint.sh", "migrate"]
    depends_on:
      - db

  actions_api:
    build: ./actions_api
    profiles: ["main", "init"]
    networks:
      - backend
    volumes:
      - ./actions_api:/usr/src/actions_api/
    env_file:
      - ./actions_api/.env
    depends_on:
      - db

  event_generator:
    build: ./event_generator
    profiles: [ "main", "init" ]
    networks:
      - backend
    volumes:
      - ./event_generator:/usr/src/event_generator/
    env_file:
      - ./event_generator/.env
    depends_on:
      - db

  nginx:
    build: ./services/nginx
    profiles: ["main", "init"]
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - static_volume:/usr/src/admin/static
    depends_on:
      - admin
      - actions_api

volumes:
  postgres_volume:
  static_volume: