version: '3'

networks:
  backend:

services:
  db:
    build: ./services/postgres
    container_name: postgres
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.env

  admin:
    build: ./admin
    networks:
      - backend
    ports:
      - 8081:8000
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    depends_on:
      - db

  actions_api:
    build: ./actions_api
    networks:
      - backend
    ports:
      - 8082:8000
    volumes:
      - ./actions_api:/usr/src/actions_api/
    env_file:
      - ./actions_api/.env
    depends_on:
      - db

volumes:
  postgres_volume:
  static_volume: