version: '3'

networks:
  proxy:
  backend:

services:
  db:
    build: ./services/postgres
    container_name: postgres
    profiles: [ "main", "init" ]
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./services/postgres/.env

  admin:
    build: ./admin
    profiles: [ "main", "start" ]
    networks:
      - proxy
      - backend
    ports:
      - 8000:8000
    volumes:
      - ./admin:/usr/src/admin/
      - static_volume:/usr/src/admin/static
    env_file:
      - ./admin/.env
    depends_on:
      - db

volumes:
  postgres_volume:
  static_volume: