version: '3.9'

services:
  rabbit_worker:
    container_name: rabbit_worker
    build:
      dockerfile: Dockerfile
      context: ./services/notification/broker_service/src
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - db

  rabbit_consumer:
    container_name: rabbit_consumer
    build:
      dockerfile: Dockerfile
      context: ./services/notification/
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
